version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: forex_prediction_backend
    ports:
      - "8080:8080"  # FastAPI endpoint
      - "8000:8000"  # Prometheus metrics
    volumes:
      - ./model_deployment:/app/model_deployment
    environment:
      - MODEL_DIR=model_deployment/model
      - MODEL_METADATA=model_deployment/model_metadata.json
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: forex_prediction_frontend
    ports:
      - "3001:80"  # Expose frontend on port 3001
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - app_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: forex_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - app_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.2
    container_name: forex_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - app_network
    restart: unless-stopped
      
  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: forex_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: