stages:
  extract:
    cmd: python data_engineering/load_data.py --output_dir data/raw --start_date ${start_date}
    deps:
      - data_engineering/load_data.py
    params:
      - start_date
    outs:
      - data/raw:
          persist: true
  
  transform:
    cmd: python data_engineering/prepare_data.py --input_dir data/raw --output_dir data/prepared --sequence_length ${sequence_length} --prediction_horizon ${prediction_horizon}
    deps:
      - data_engineering/prepare_data.py
      - data/raw
    params:
      - sequence_length
      - prediction_horizon
    outs:
      - data/prepared:
          persist: true
      - data/test:
          persist: true
    
  hyperparameter_tuning:
    cmd: python model_creation/tuning.py --data_path data/prepared/USD_INR_transformed.csv --train_sequence ${train_sequence} --mlflow_tracking_uri ${mlflow_tracking_uri} --experiment_name ${experiment_name}_tuning
    deps:
      - model_creation/tuning.py
      - data/prepared/USD_INR_transformed.csv
    params:
      - train_sequence
      - mlflow_tracking_uri
      - experiment_name
    outs:
      - model_creation/tuning_results:
          persist: true
  
  train:
    cmd: >
      python model_creation/train.py 
      --data_path data/prepared/USD_INR_transformed.csv
      --train_sequence ${train_sequence} 
      --hidden_size ${model.hidden_size} 
      --num_layers ${model.num_layers} 
      --dropout ${model.dropout} 
      --batch_size ${training.batch_size} 
      --learning_rate ${training.learning_rate} 
      --num_epochs ${training.num_epochs} 
      --mlflow_tracking_uri ${mlflow_tracking_uri} 
      --experiment_name ${experiment_name} 
      --model_dir models
    deps:
      - model_creation/train.py
      - data/prepared/USD_INR_transformed.csv
      - tuning_results/best_params.json
    params:
      - train_sequence
      - model
      - training
      - mlflow_tracking_uri
      - experiment_name
    outs:
      - model_creation/models:
          persist: true
  
  evaluate:
    cmd: >
      python model_creation/evaluation.py 
      --model_run_id $(cat model_creation/tuning_results/best_params.json | jq -r '.run_id') 
      --data_path data/test/USD_INR_transformed.csv
      --test_sequence ${test_sequence} 
      --reference_data_path data/prepared/USD_INR_transformed.csv 
      --mlflow_tracking_uri ${mlflow_tracking_uri} 
      --output_dir model_creation/evaluation_results
    deps:
      - model_creation/evaluation.py
      - data/test/USD_INR_transformed.csv
      - data/prepared/USD_INR_transformed.csv
      - model_creation/tuning_results
    params:
      - test_sequence
      - mlflow_tracking_uri
    outs:
      - model_creation/evaluation_results:
          persist: true
  
  # check_drift:
  #   cmd: >
  #     python model_creation/drift.py 
  #     --evaluation_results evaluation_results 
  #     --threshold ${drift.threshold} 
  #     --trigger_rebuild ${drift.trigger_rebuild}
  #   deps:
  #     - model_creation/drift.py
  #     - evaluation_results
  #     - utils/logger.py
  #   params:
  #     - drift.threshold
  #     - drift.trigger_rebuild
  #   outs:
  #     - model_monitoring:
  #         persist: true
  
  save_model:
    cmd: >
      python model_creation/save_model.py
      --run_id $(cat model_creation/tuning_results/best_params.json | jq -r '.run_id')
      --mlflow_tracking_uri ${mlflow_tracking_uri}
      --output_dir model_deployment
    deps:
      - model_creation/save_model.py
      - model_creation/tuning_results/best_params.json
    params:
      - mlflow_tracking_uri
    outs:
      - model_deployment:
          persist: true
    always_changed: true
