stages:
  extract:
    cmd: python data_engineering/load_data.py --output_dir data/raw --start_date ${start_date}
    deps:
      - data_engineering/load_data.py
    params:
      - start_date
    outs:
      - data/raw:
          persist: true
  
  transform:
    cmd: python data_engineering/prepare_data.py --input_dir data/raw --output_dir data/prepared --sequence_length ${sequence_length} --prediction_horizon ${prediction_horizon}
    deps:
      - data_engineering/prepare_data.py
      - data/raw
    params:
      - sequence_length
      - prediction_horizon
    outs:
      - data/prepared:
          persist: true